name: Android Gradle Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: ./gradlew build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bminer-debug-apk
          path: build/outputs/apk/debug/*.apk
